[Definition]
# Fail2ban filter for Docker Registry authentication failures

failregex = ^<HOST> .* "(GET|POST|PUT|DELETE|HEAD) /v2/.* HTTP/.*" 401 .*$
            ^<HOST> .* "(GET|POST|PUT|DELETE|HEAD) /v2/.* HTTP/.*" 403 .*$

ignoreregex =

datepattern = %%d/%%b/%%Y:%%H:%%M:%%S
