[Definition]
# Fail2ban filter to block bad user agents (bots)

failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*"(?:%(badbots)s|%(badbotscustom)s)"$

badbots = Wget|libwww-perl|python-requests|libwww|nikto|Atomic_Email_Hunter|GetRight|FrontPage|TurnitinBot|Baiduspider|Sogou|Java|psbot|pythonurllib|Indy Library

badbotscustom = masscan|nmap|sqlmap|acunetix|metasploit|360spider|semrush|mj12bot|ahrefsbot

ignoreregex =
